# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180525_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u8001\u5e08\u5934\u50cf'),
        ),
    ]
